/* tslint:disable */
/* eslint-disable */
/**
 * Jaipur
 * API pour le jeu de société Jaipur
 *
 * The version of the OpenAPI document: 1.0
 * Contact: julien@usson.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BonusTokens
 */
export interface BonusTokens {
    /**
     * 
     * @type {number}
     * @memberof BonusTokens
     */
    _3: number;
    /**
     * 
     * @type {number}
     * @memberof BonusTokens
     */
    _4: number;
    /**
     * 
     * @type {number}
     * @memberof BonusTokens
     */
    _5: number;
}

export function BonusTokensFromJSON(json: any): BonusTokens {
    return BonusTokensFromJSONTyped(json, false);
}

export function BonusTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): BonusTokens {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_3': json['3'],
        '_4': json['4'],
        '_5': json['5'],
    };
}

export function BonusTokensToJSON(value?: BonusTokens | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '3': value._3,
        '4': value._4,
        '5': value._5,
    };
}


