/* tslint:disable */
/* eslint-disable */
/**
 * Jaipur
 * API pour le jeu de société Jaipur
 *
 * The version of the OpenAPI document: 1.0
 * Contact: julien@usson.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGame
 */
export interface CreateGame {
    /**
     * 
     * @type {string}
     * @memberof CreateGame
     */
    name?: string;
}

export function CreateGameFromJSON(json: any): CreateGame {
    return CreateGameFromJSONTyped(json, false);
}

export function CreateGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGame {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CreateGameToJSON(value?: CreateGame | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


