/* tslint:disable */
/* eslint-disable */
/**
 * Jaipur
 * API pour le jeu de société Jaipur
 *
 * The version of the OpenAPI document: 1.0
 * Contact: julien@usson.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A game with minimal infos
 * @export
 * @interface GamePreview
 */
export interface GamePreview {
    /**
     * 
     * @type {number}
     * @memberof GamePreview
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GamePreview
     */
    name: string;
}

export function GamePreviewFromJSON(json: any): GamePreview {
    return GamePreviewFromJSONTyped(json, false);
}

export function GamePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePreview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function GamePreviewToJSON(value?: GamePreview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


