/* tslint:disable */
/* eslint-disable */
/**
 * Jaipur
 * API pour le jeu de société Jaipur
 *
 * The version of the OpenAPI document: 1.0
 * Contact: julien@usson.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Good {
    Diamonds = 'diamonds',
    Gold = 'gold',
    Silver = 'silver',
    Cloth = 'cloth',
    Spice = 'spice',
    Leather = 'leather'
}

export function GoodFromJSON(json: any): Good {
    return GoodFromJSONTyped(json, false);
}

export function GoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Good {
    return json as Good;
}

export function GoodToJSON(value?: Good | null): any {
    return value as any;
}

