/* tslint:disable */
/* eslint-disable */
/**
 * Jaipur
 * API pour le jeu de société Jaipur
 *
 * The version of the OpenAPI document: 1.0
 * Contact: julien@usson.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Healthstatus
 */
export interface Healthstatus {
    /**
     * 
     * @type {string}
     * @memberof Healthstatus
     */
    health: string;
}

export function HealthstatusFromJSON(json: any): Healthstatus {
    return HealthstatusFromJSONTyped(json, false);
}

export function HealthstatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): Healthstatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'health': json['health'],
    };
}

export function HealthstatusToJSON(value?: Healthstatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'health': value.health,
    };
}


