/* tslint:disable */
/* eslint-disable */
/**
 * Jaipur
 * API pour le jeu de société Jaipur
 *
 * The version of the OpenAPI document: 1.0
 * Contact: julien@usson.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Good,
    GoodFromJSON,
    GoodFromJSONTyped,
    GoodToJSON,
} from './';

/**
 * 
 * @export
 * @interface TakeGoodPayload
 */
export interface TakeGoodPayload {
    /**
     * 
     * @type {Good}
     * @memberof TakeGoodPayload
     */
    good: Good;
}

export function TakeGoodPayloadFromJSON(json: any): TakeGoodPayload {
    return TakeGoodPayloadFromJSONTyped(json, false);
}

export function TakeGoodPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TakeGoodPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'good': GoodFromJSON(json['good']),
    };
}

export function TakeGoodPayloadToJSON(value?: TakeGoodPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'good': GoodToJSON(value.good),
    };
}


